name: langchain_gemini
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2023.11.17=hf0a4a13_0
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.44.2=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4=h463b476_2
  - openssl=3.2.0=h0d3ecfb_1
  - pip=23.3.2=pyhd8ed1ab_0
  - python=3.12.1=hdf0ec26_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tzdata=2023d=h0c530f3_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
    - annotated-types==0.6.0
    - anyio==4.2.0
    - appnope==0.1.3
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - cachetools==5.3.2
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - comm==0.2.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - fqdn==1.5.1
    - google-ai-generativelanguage==0.4.0
    - google-api-core==2.15.0
    - google-auth==2.27.0
    - google-generativeai==0.3.2
    - googleapis-common-protos==1.62.0
    - grpcio==1.60.0
    - grpcio-status==1.60.0
    - idna==3.6
    - ipykernel==6.29.0
    - ipython==8.20.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - json5==0.9.14
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.0
    - jupyter-console==6.6.3
    - jupyter-core==5.7.1
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.2
    - jupyter-server==2.12.5
    - jupyter-server-terminals==0.5.2
    - jupyterlab==4.0.11
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.2
    - jupyterlab-widgets==3.0.9
    - langchain-core==0.1.16
    - langchain-google-genai==0.0.6
    - langsmith==0.0.84
    - markupsafe==2.1.4
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - nbclient==0.9.0
    - nbconvert==7.14.2
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - notebook==7.0.7
    - notebook-shim==0.2.3
    - overrides==7.7.0
    - packaging==23.2
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pexpect==4.9.0
    - pillow==10.2.0
    - platformdirs==4.1.0
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.43
    - proto-plus==1.23.0
    - protobuf==4.25.2
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - pygments==2.17.2
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - referencing==0.33.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.17.1
    - rsa==4.9
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.6.3
    - tenacity==8.2.3
    - terminado==0.18.0
    - tinycss2==1.2.1
    - tornado==6.4
    - tqdm==4.66.1
    - traitlets==5.14.1
    - types-python-dateutil==2.8.19.20240106
    - typing-extensions==4.9.0
    - uri-template==1.3.0
    - urllib3==2.1.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - widgetsnbextension==4.0.9
prefix: ~/miniforge3/envs/langchain_gemini
