name: langchain_gemini
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2024.2.2=hf0a4a13_0
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.44.2=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4=h463b476_2
  - openssl=3.2.1=h0d3ecfb_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.11.7=hdf0ec26_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - altair==5.2.0
    - annotated-types==0.6.0
    - anyio==4.2.0
    - appnope==0.1.3
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blinker==1.7.0
    - cachetools==5.3.2
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - comm==0.2.1
    - contourpy==1.2.0
    - cycler==0.12.1
    - dataclasses-json==0.6.3
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==2.0.1
    - faiss-cpu==1.7.4
    - fastjsonschema==2.19.1
    - filelock==3.13.1
    - fonttools==4.47.2
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.41
    - google-ai-generativelanguage==0.4.0
    - google-api-core==2.15.0
    - google-auth==2.27.0
    - google-cloud-aiplatform==1.40.0
    - google-cloud-bigquery==3.17.1
    - google-cloud-core==2.4.1
    - google-cloud-resource-manager==1.12.0
    - google-cloud-storage==2.14.0
    - google-crc32c==1.5.0
    - google-generativeai==0.3.2
    - google-resumable-media==2.7.0
    - googleapis-common-protos==1.62.0
    - grpc-google-iam-v1==0.13.0
    - grpcio==1.60.0
    - grpcio-status==1.60.0
    - huggingface-hub==0.20.3
    - idna==3.6
    - importlib-metadata==7.0.1
    - ipykernel==6.29.0
    - ipython==8.20.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.0
    - jupyter-console==6.6.3
    - jupyter-core==5.7.1
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.2
    - jupyter-server==2.12.5
    - jupyter-server-terminals==0.5.2
    - jupyterlab==4.0.11
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.2
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.5
    - langchain==0.1.4
    - langchain-community==0.0.16
    - langchain-core==0.1.16
    - langchain-google-genai==0.0.6
    - langchain-google-vertexai==0.0.3
    - langsmith==0.0.84
    - markdown-it-py==3.0.0
    - markupsafe==2.1.4
    - marshmallow==3.20.2
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==3.0.2
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - nbclient==0.9.0
    - nbconvert==7.14.2
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - notebook==7.0.7
    - notebook-shim==0.2.3
    - numpy==1.26.3
    - overrides==7.7.0
    - packaging==23.2
    - pandas==2.2.0
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pexpect==4.9.0
    - pillow==10.2.0
    - pinecone-client==3.0.2
    - platformdirs==4.1.0
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.43
    - proto-plus==1.23.0
    - protobuf==4.25.2
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==15.0.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - pydeck==0.8.1b0
    - pygments==2.17.2
    - pyparsing==3.1.1
    - pypdf2==3.0.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - pytube==15.0.0
    - pytz==2023.4
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - referencing==0.33.0
    - regex==2023.12.25
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.0
    - rpds-py==0.17.1
    - rsa==4.9
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - send2trash==1.8.2
    - shapely==2.0.2
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - sqlalchemy==2.0.25
    - stack-data==0.6.3
    - streamlit==1.31.0
    - tenacity==8.2.3
    - terminado==0.18.0
    - threadpoolctl==3.2.0
    - tiktoken==0.5.2
    - tinycss2==1.2.1
    - toml==0.10.2
    - toolz==0.12.1
    - tornado==6.4
    - tqdm==4.66.1
    - traitlets==5.14.1
    - types-protobuf==4.24.0.20240129
    - types-python-dateutil==2.8.19.20240106
    - types-requests==2.31.0.20240125
    - typing-extensions==4.9.0
    - typing-inspect==0.9.0
    - tzdata==2023.4
    - tzlocal==5.2
    - uri-template==1.3.0
    - urllib3==2.1.0
    - validators==0.22.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - widgetsnbextension==4.0.9
    - yarl==1.9.4
    - youtube-transcript-api==0.6.2
    - zipp==3.17.0
prefix: /Users/ebarakoji/miniforge3/envs/langchain_gemini
